---
title: "Full_Color_Band_Processing.Rmd"
output: html_document
date: "2024-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This Rmarkdown file is to create a loop that generates and cleans the color band data for the entirety of Connecticut
```{r}
library(raster)
library(sf)
library(foreach)
library(doParallel)
library(stringr)
library(dplyr)
```

Let's load in the shapefile arguments
```{r}
us_shp <- read_sf("/Volumes/Seagate Portable Drive/Shapefiles/tl_2022_us_state/tl_2022_us_state.shp")

#Subset on the Connecticut shapefile
ct_shp <- us_shp[us_shp$NAME == "Connecticut",]

#Get the lon-lat crs
lon_lat_crs <- st_crs(ct_shp)

#Get the CRS of the shapefile
crsSH <- CRS("+init=epsg:4269")

#We need to load in a sample LST file for resampling
lst_sample <- "/Volumes/Seagate Portable Drive/0.raw_data/0.2.1.LST_MOD11A1/MOD11A1.061_LST_Day_1km_doy2019028_aid0001.tif"
lst_raster <- raster::brick(lst_sample)
lst_raster <- raster::projectRaster(lst_raster, crs = crsSH) #Project the raster
lst_raster <- raster::mask(lst_raster, mask = ct_shp) #Mask the raster
```

Let's get the list of files for each
```{r}
b01_files <- list.files(path = "/Volumes/Seagate Portable Drive/0.raw_data/0.7.Color_band/b01", pattern = "b01", full.names = TRUE)
b03_files <- list.files(path = "/Volumes/Seagate Portable Drive/0.raw_data/0.7.Color_band/b03", pattern = "b03", full.names = TRUE)
b04_files <- list.files(path = "/Volumes/Seagate Portable Drive/0.raw_data/0.7.Color_band/b04", pattern = "b04", full.names = TRUE)
```

We need to also get the date. Now we just need to turn this into a loop.
```{r}
cb_vars <- c("b01", "b03", "b04")
cb_files <- list(b01_files, b03_files, b04_files)

#Set up parallel backend
cl <- makeCluster(detectCores() - 1)
registerDoParallel(cl)

for(i in 1:3){
  #Get the color band data variable name and the relevant files
  var_name <- cb_vars[i]
  file_list <- cb_files[[i]]
  
  #Create the parallel processing loop
  cb_data <- data.frame()
  cb_data <- foreach(file = file_list, .combine = rbind) %dopar% {
    #Load in the data, get the values and correctly scale them. Note, we do not mask because that introduces more NAs than we already have
    raster_data <- raster::brick(file)
    raster_data <- raster::projectRaster(raster_data, crs = crsSH) #Project the raster to lonlat
    raster_data <- raster::mask(raster_data, mask = ct_shp) #Mask the raster with the shapefile
    
    #Now we perform resampling
    raster_data <- raster::resample(raster_data, lst_raster, method = "bilinear")
  
    values <- data.frame(raster::values(raster_data))
    values[values < -100] <- NA
    values <- values * 0.0001
    
    #Get the coordinates and cbind them with the values
    coords <- data.frame(raster::coordinates(raster_data))
    raster_data <- cbind(coords, values)
    
    #Create a column to get the relevant grid ids, this part is from the weather station code
    #raster_data$grid.id <- paste0(get_last_three(raster_data$x), "_", get_last_three(raster_data$y))
    
    #Now we work on creating a date column. First use regular expressions to get the relevant substring and then split it.
    date <- regmatches(file, regexpr("doy[0-9]{7}", file))
    year <- as.numeric(substr(date, 4, 7))
    doy <- as.numeric(substr(date, 8, 10))
    
    #Now we create the date column
    raster_data$Date <- as.Date(doy - 1, origin = paste0(year, "-01-01"))
    
    #Rename the columns
    names(raster_data) <- c("Longitude", "Latitude", var_name, "Date")
    
    #Return the data set for it to be rbinded
    return(raster_data)
  }
  
  #Now we need to create a file path and save the data as an RDS file
  save_path <- paste0("/Volumes/Seagate Portable Drive/3.clean_data/MOD09GA_Color_Band_", var_name, ".rds")
  saveRDS(cb_data, file = save_path)
}

#Stop cluster
stopCluster(cl)
```

Testing the data. Seems okay
```{r}
test <- readRDS("/Volumes/Seagate Portable Drive/3.clean_data/MOD09GA_Color_Band_b01.rds")
na.omit(test)
```





